#!/usr/bin/env node
/**
 * Runs a Supabase CLI database command against the project described by the
 * local credential file, without ever printing the credentials.
 *
 * The credential file is gitignored and lives outside version control on
 * purpose (docs/SECURITY.md). Point CREDENTIALS_FILE at wherever you keep it.
 *
 *   node scripts/db.mjs push          # apply pending migrations
 *   node scripts/db.mjs list          # show applied vs pending
 *   node scripts/db.mjs types         # regenerate src/lib/supabase/types.ts
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const command = process.argv[2] ?? 'list';
if (
  command === 'push' &&
  (!process.env.CI || process.env.GITHUB_ACTIONS !== 'true')
) {
  console.error(
    'Hosted migration promotion is CI-only. Use the protected promotion workflow.'
  );
  process.exit(1);
}
const CREDENTIALS_FILE =
  process.env.CREDENTIALS_FILE ?? join(ROOT, 'docs', 'supa_keys.md');

if (!existsSync(CREDENTIALS_FILE)) {
  console.error(`No credential file at ${CREDENTIALS_FILE}.`);
  console.error('Set CREDENTIALS_FILE to its location.');
  process.exit(1);
}

const credentials = Object.fromEntries(
  readFileSync(CREDENTIALS_FILE, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.includes('='))
    .map((line) => {
      const index = line.indexOf('=');
      return [line.slice(0, index).trim(), line.slice(index + 1).trim()];
    })
);

const password = credentials.supabase_password;
const projectId = credentials.project_id;

if (!password || !projectId) {
  console.error('Credential file needs supabase_password and project_id.');
  process.exit(1);
}

// The password is user-chosen and routinely contains @ ! # — characters that
// silently corrupt a connection URL unless encoded.
const dbUrl = `postgresql://postgres:${encodeURIComponent(password)}@db.${projectId}.supabase.co:5432/postgres`;

const ARGS = {
  push: ['supabase', 'db', 'push', '--db-url', dbUrl],
  list: ['supabase', 'migration', 'list', '--db-url', dbUrl],
  types: ['supabase', 'gen', 'types', 'typescript', '--db-url', dbUrl],
};

if (!(command in ARGS)) {
  console.error(`Unknown command "${command}". Use: push | list | types`);
  process.exit(1);
}

const result = spawnSync('npx', ['--yes', ...ARGS[command]], {
  cwd: ROOT,
  encoding: 'utf8',
  shell: true,
  input: 'Y\n',
});

// Never let the URL reach a log, an error message or a CI transcript.
const redact = (text) =>
  (text ?? '').split(dbUrl).join('postgresql://***:***@***/postgres');

if (command === 'types' && result.status === 0) {
  const { writeFileSync } = await import('node:fs');
  const header = `/**
 * Generated by: npm run db:types
 * Do not edit by hand.
 */
`;
  writeFileSync(
    join(ROOT, 'src', 'lib', 'supabase', 'types.ts'),
    header + result.stdout
  );
  console.log('Wrote src/lib/supabase/types.ts');
} else if (result.stdout) {
  console.log(redact(result.stdout));
}

if (result.stderr) {
  console.error(redact(result.stderr));
}

process.exit(result.status ?? 1);
